name: All Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  all-checks:
    name: All Checks Status
    runs-on: ubuntu-latest
    needs: 
      - rust-check
      - rust-test
      - rust-fmt
      - rust-clippy
      - frontend-build
      - security
    steps:
      - name: All checks passed
        run: echo "All required checks have passed!"

  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo check -p apalis-board-types
          cargo check -p apalis-board-api --all-features
          cargo check -p apalis-board --all-features

  rust-test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo test -p apalis-board-types
          cargo test -p apalis-board-api --all-features

  rust-fmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  rust-clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo clippy -p apalis-board-types -- -D warnings
          cargo clippy -p apalis-board-api --all-features -- -D warnings
          cargo clippy -p apalis-board --all-features -- -D warnings

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/local/bin/
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates/board
      - run: npm ci
      - run: |
          cd crates/board
          trunk build --release

  security:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-audit
      - run: cargo audit --deny warnings || true
